CREATE TABLE recurring_consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status TEXT NOT NULL,
    status_updated_at TIMESTAMPTZ NOT NULL,
    authorized_at TIMESTAMPTZ,
    approval_due_at DATE,
    expires_at TIMESTAMPTZ,
    user_id UUID NOT NULL REFERENCES mock_users(id),
    user_identification TEXT NOT NULL,
	user_rel            TEXT NOT NULL,
	business_identification TEXT,
	business_rel TEXT,
    creditors JSONB NOT NULL,
    additional_info TEXT,
    configuration JSONB NOT NULL,
    risk_signals JSONB,
    account_id UUID REFERENCES accounts(id),
    rejection JSONB,
    revocation JSONB,
    client_id TEXT NOT NULL REFERENCES oauth_clients(id),
    org_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recurring_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consent_id UUID NOT NULL REFERENCES recurring_consents(id),
    end_to_end_id TEXT NOT NULL,
    date DATE NOT NULL,
    status TEXT NOT NULL,
    status_updated_at TIMESTAMPTZ NOT NULL,
    amount TEXT NOT NULL,
    currency TEXT NOT NULL,
    creditor_account_isbp TEXT NOT NULL,
    creditor_account_issuer TEXT,
    creditor_account_number TEXT NOT NULL,
    creditor_account_type TEXT NOT NULL,
    remittance_information TEXT,
    cnpj_initiator TEXT NOT NULL,
    ibge_town_code TEXT,
    authorisation_flow TEXT,
    local_instrument TEXT NOT NULL,
    proxy TEXT,
    transaction_identification TEXT,
    document_identification TEXT NOT NULL,
    document_rel TEXT NOT NULL,
    original_id UUID REFERENCES recurring_payments(id),
    reference TEXT,
    risk_signals JSONB,
    client_id TEXT NOT NULL REFERENCES oauth_clients(id),
    account_id UUID REFERENCES accounts(id),
    rejection JSONB,
    cancellation JSONB,

    org_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
