services:

  mockbank:
    profiles:
      - main
    build: .
    volumes:
      - ./keys/:/app/keys/
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  
  reverse-proxy:
    profiles:
      - dev
      - main
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keys/server.crt:/etc/nginx/ssl/server.crt
      - ./keys/server.key:/etc/nginx/ssl/server.key
      - ./keys/client_ca.crt:/etc/nginx/ssl/client_ca.crt
      - ./logs/:/var/log/nginx/
      - ./participants.json:/etc/nginx/mocks/participants.json
      - ./keys/client_one_pub.jwks:/etc/nginx/mocks/client_one_pub.jwks
    ports:
      - 443:443
    networks:
      default:
        aliases:
          - mockbank.local
          - auth.mockbank.local
          - matls-auth.mockbank.local
          - matls-api.mockbank.local
          - directory

  cs-httpd:
    profiles:
      - conformance
    build:
      context: ./conformance-suite/httpd
      dockerfile: Dockerfile-static
    ports:
     - "8443:8443"
    volumes:
     - ./conformance-suite/src/main/resources/:/usr/local/apache2/htdocs/
    depends_on:
     - cs-server
    networks:
      default:
        aliases:
          - localhost.emobix.co.uk

  cs-server:
    profiles:
      - conformance
    hostname: server
    image: openjdk:17-jdk-slim
    build:
      context: ./conformance-suite/server-dev
    ports:
     - "9999:9999"
    volumes:
     - ./conformance-suite/target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      -Dcom.sun.net.ssl.checkRevocation=false -Dcom.sun.net.ssl.trustStoreType=JKS -Dcom.sun.net.ssl.trustStorePassword=changeit
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
      --fintechlabs.yacs.directory.uri=http://directory/participants
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
  
  cs-builder:
    profiles:
      - build
    image: maven:3-openjdk-17
    volumes:
      - maven-cache:/root/.m2
      - ./conformance-suite:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn -B clean package -DskipTests=true

volumes:
  maven-cache:
    driver: local