services:
  mockbank:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=LOCAL
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_healthy
      psql:
        condition: service_started

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=iam,ssm,secretsmanager
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testdata/setup-localstack.sh:/etc/localstack/init/ready.d/setup.sh:ro
      - ./keys/:/keys:ro
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "sleep 2 && curl -f http://localhost:4566/_localstack/health || exit 1",
        ]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s

  psql:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mockbank
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations/000001_setup.up.sql:/docker-entrypoint-initdb.d/000001_setup.up.sql:ro
      - ./testdata/seed.sql:/docker-entrypoint-initdb.d/999999_seed.sql:ro
    networks:
      default:
        aliases:
          - psql.local

  mockgw:
    build:
      context: ./cmd/mockgw
    volumes:
      - ./keys/server.crt:/mocks/server.crt:ro
      - ./keys/server.key:/mocks/server.key:ro
      - ./keys/client_one_pub.jwks:/mocks/client.jwks:ro
      - ./keys/ca.crt:/mocks/ca.crt:ro
      - ./keys/org_pub.jwks:/mocks/org.jwks:ro
      - ./testdata/participants.json:/mocks/participants.json:ro
      - ./testdata/directory_jwks.json:/mocks/directory_jwks.json:ro
      - ./testdata/directory_well_known.json:/mocks/directory_well_known.json:ro
      - ./testdata/id_token.json:/mocks/id_token.json:ro
      - ./testdata/software_statement.json:/mocks/software_statement.json:ro
      - ./testdata/software_statement_jwks.json:/mocks/software_statement_jwks.json:ro
    ports:
      - 443:443
    networks:
      default:
        aliases:
          - mockbank.local
          - app.mockbank.local
          - auth.mockbank.local
          - matls-auth.mockbank.local
          - api.mockbank.local
          - matls-api.mockbank.local
          - directory.local
          - matls-directory.local
          - keystore.local

  cs-httpd:
    profiles:
      - conformance
    build:
      context: ./conformance-suite/httpd
      dockerfile: Dockerfile-static
    ports:
      - "8443:8443"
    volumes:
      - ./conformance-suite/src/main/resources/:/usr/local/apache2/htdocs/
    depends_on:
      - cs-server
    networks:
      default:
        aliases:
          - localhost.emobix.co.uk

  cs-server:
    profiles:
      - conformance
    hostname: server
    image: openjdk:17-jdk-slim
    build:
      context: ./conformance-suite/server-dev
    ports:
      - "9999:9999"
    volumes:
      - ./conformance-suite/target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      -Dcom.sun.net.ssl.checkRevocation=false -Dcom.sun.net.ssl.trustStoreType=JKS -Dcom.sun.net.ssl.trustStorePassword=changeit
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
      --fintechlabs.yacs.directory.uri=http://directory.local/participants
    depends_on:
      - cs-mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  cs-mongodb:
    profiles:
      - conformance
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - mongodb

  cs-builder:
    profiles:
      - build
    image: maven:3-openjdk-17
    volumes:
      - maven-cache:/root/.m2
      - ./conformance-suite:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn -B clean package -DskipTests=true

volumes:
  maven-cache:
    driver: local
