services:
  mockbank:
    profiles:
      - main
    build: .
    environment:
      - DB_CONNECTION_STRING=postgres://admin:pass@psql:5432/mockbank?sslmode=disable
    volumes:
      - ./keys/:/app/keys/

  psql:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mockbank
    ports:
      - "5432:5432"

  mockgw:
    profiles:
      - debug
      - main
    build:
      context: ./cmd/mockgw
    volumes:
      - ./keys/server.crt:/mocks/server.crt
      - ./keys/server.key:/mocks/server.key
      - ./keys/client_one_pub.jwks:/mocks/client.jwks
      - ./keys/client_ca.crt:/mocks/client_ca.crt
      - ./mocks/participants.json:/mocks/participants.json
      - ./mocks/directory_jwks.json:/mocks/directory_jwks.json
      - ./mocks/directory_well_known.json:/mocks/directory_well_known.json
      - ./mocks/id_token.json:/mocks/id_token.json
      - ./mocks/software_statement.json:/mocks/software_statement.json
      - ./mocks/keystore_jwks.json:/mocks/keystore_jwks.json
    ports:
      - 443:443
    networks:
      default:
        aliases:
          - mockbank.local
          - app.mockbank.local
          - auth.mockbank.local
          - matls-auth.mockbank.local
          - api.mockbank.local
          - matls-api.mockbank.local
          - directory.local
          - keystore.local

  cs-httpd:
    profiles:
      - conformance
    build:
      context: ./conformance-suite/httpd
      dockerfile: Dockerfile-static
    ports:
      - "8443:8443"
    volumes:
      - ./conformance-suite/src/main/resources/:/usr/local/apache2/htdocs/
    depends_on:
      - cs-server
    networks:
      default:
        aliases:
          - localhost.emobix.co.uk

  cs-server:
    profiles:
      - conformance
    hostname: server
    image: openjdk:17-jdk-slim
    build:
      context: ./conformance-suite/server-dev
    ports:
      - "9999:9999"
    volumes:
      - ./conformance-suite/target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      -Dcom.sun.net.ssl.checkRevocation=false -Dcom.sun.net.ssl.trustStoreType=JKS -Dcom.sun.net.ssl.trustStorePassword=changeit
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
      --fintechlabs.yacs.directory.uri=http://directory.local/participants
    depends_on:
      - cs-mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  cs-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - mongodb

  cs-builder:
    profiles:
      - build
    image: maven:3-openjdk-17
    volumes:
      - maven-cache:/root/.m2
      - ./conformance-suite:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn -B clean package -DskipTests=true

volumes:
  maven-cache:
    driver: local
