//go:build go1.22

// Package app provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240908200014-2be24b11ae0f DO NOT EDIT.
package app

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/luiky/mock-bank/internal/api"
	"github.com/luiky/mock-bank/internal/timex"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	SessionCookieScopes = "SessionCookie.Scopes"
)

// AccountRequest defines model for AccountRequest.
type AccountRequest struct {
	Data struct {
		AutomaticallyInvestedAmount string  `json:"automaticallyInvestedAmount"`
		AvailableAmount             string  `json:"availableAmount"`
		BlockedAmount               string  `json:"blockedAmount"`
		Number                      string  `json:"number"`
		OverdraftLimitContracted    *string `json:"overdraftLimitContracted,omitempty"`
		OverdraftLimitUnarraged     *string `json:"overdraftLimitUnarraged,omitempty"`
		OverdraftLimitUsed          *string `json:"overdraftLimitUsed,omitempty"`
		Subtype                     string  `json:"subtype"`
		Type                        string  `json:"type"`
	} `json:"data"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Data struct {
		AccountID  string  `json:"accountId"`
		BranchCode *string `json:"branchCode,omitempty"`
		CheckDigit string  `json:"checkDigit"`
		CompeCode  string  `json:"compeCode"`
		Number     string  `json:"number"`
		Type       string  `json:"type"`
	} `json:"data"`
}

// AccountsResponse defines model for AccountsResponse.
type AccountsResponse struct {
	Data []struct {
		AccountID  string  `json:"accountId"`
		BranchCode *string `json:"branchCode,omitempty"`
		CheckDigit string  `json:"checkDigit"`
		Number     string  `json:"number"`
		Type       string  `json:"type"`
	} `json:"data"`
	Links *api.Links `json:"links,omitempty"`
	Meta  *api.Meta  `json:"meta,omitempty"`
}

// AuthURLResponse defines model for AuthUrlResponse.
type AuthURLResponse struct {
	Data struct {
		URL string `json:"url"`
	} `json:"data"`
}

// ConsentsResponse defines model for ConsentsResponse.
type ConsentsResponse struct {
	Data []struct {
		ClientID             string          `json:"clientId"`
		ConsentID            string          `json:"consentId"`
		CreationDateTime     timex.DateTime  `json:"creationDateTime"`
		ExpirationDateTime   *timex.DateTime `json:"expirationDateTime,omitempty"`
		Permissions          []string        `json:"permissions"`
		RejectedBy           *string         `json:"rejectedBy,omitempty"`
		RejectionReason      *string         `json:"rejectionReason,omitempty"`
		Status               string          `json:"status"`
		StatusUpdateDateTime timex.DateTime  `json:"statusUpdateDateTime"`
		UserID               string          `json:"userId"`
	} `json:"data"`
	Links *api.Links `json:"links,omitempty"`
	Meta  *api.Meta  `json:"meta,omitempty"`
}

// MockUserRequest defines model for MockUserRequest.
type MockUserRequest struct {
	Data struct {
		Cpf      string  `json:"cpf"`
		Name     string  `json:"name"`
		Password *string `json:"password,omitempty"`
		Username string  `json:"username"`
	} `json:"data"`
}

// MockUserResponse defines model for MockUserResponse.
type MockUserResponse struct {
	Data struct {
		Cpf      string  `json:"cpf"`
		ID       string  `json:"id"`
		Name     string  `json:"name"`
		Password *string `json:"password,omitempty"`
		Username string  `json:"username"`
	} `json:"data"`
}

// MockUsersResponse defines model for MockUsersResponse.
type MockUsersResponse struct {
	Data []struct {
		Cpf      string `json:"cpf"`
		ID       string `json:"id"`
		Name     string `json:"name"`
		Username string `json:"username"`
	} `json:"data"`
	Links *api.Links `json:"links,omitempty"`
	Meta  *api.Meta  `json:"meta,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data struct {
		Organizations []struct {
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"organizations"`
		Username string `json:"username"`
	} `json:"data"`
}

// AccountID defines model for accountId.
type AccountID = string

// MockUserID defines model for mockUserId.
type MockUserID = string

// OrganizationID defines model for organizationId.
type OrganizationID = string

// Page defines model for page.
type Page = int32

// PageSize defines model for pageSize.
type PageSize = int32

// HandleDirectoryCallbackParams defines parameters for HandleDirectoryCallback.
type HandleDirectoryCallbackParams struct {
	IDToken string `form:"id_token" json:"id_token"`
}

// GetMockUsersParams defines parameters for GetMockUsers.
type GetMockUsersParams struct {
	// Page Número da página que está sendo requisitada (o valor da primeira página é 1).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Quantidade total de registros por páginas.
	PageSize *PageSize `form:"page-size,omitempty" json:"page-size,omitempty"`
}

// GetAccountsParams defines parameters for GetAccounts.
type GetAccountsParams struct {
	// Page Número da página que está sendo requisitada (o valor da primeira página é 1).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Quantidade total de registros por páginas.
	PageSize *PageSize `form:"page-size,omitempty" json:"page-size,omitempty"`
}

// GetConsentsParams defines parameters for GetConsents.
type GetConsentsParams struct {
	// Page Número da página que está sendo requisitada (o valor da primeira página é 1).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Quantidade total de registros por páginas.
	PageSize *PageSize `form:"page-size,omitempty" json:"page-size,omitempty"`
}

// CreateMockUserJSONRequestBody defines body for CreateMockUser for application/json ContentType.
type CreateMockUserJSONRequestBody = MockUserRequest

// UpdateMockUserJSONRequestBody defines body for UpdateMockUser for application/json ContentType.
type UpdateMockUserJSONRequestBody = MockUserRequest

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = AccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the authentication URL for the directory service
	// (GET /api/directory/auth-url)
	GetDirectoryAuthURL(w http.ResponseWriter, r *http.Request)

	// (GET /api/directory/callback)
	HandleDirectoryCallback(w http.ResponseWriter, r *http.Request, params HandleDirectoryCallbackParams)
	// Logout the current user
	// (POST /api/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Get current user information
	// (GET /api/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List mock users in an organization
	// (GET /api/orgs/{orgId}/users)
	GetMockUsers(w http.ResponseWriter, r *http.Request, orgID OrganizationID, params GetMockUsersParams)
	// Create a new user in an organization
	// (POST /api/orgs/{orgId}/users)
	CreateMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID)
	// Delete a mock user in an organization
	// (DELETE /api/orgs/{orgId}/users/{userId})
	DeleteMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID)
	// Update a user in an organization
	// (PUT /api/orgs/{orgId}/users/{userId})
	UpdateMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID)
	// Get accounts of a user
	// (GET /api/orgs/{orgId}/users/{userId}/accounts)
	GetAccounts(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, params GetAccountsParams)
	// Create a new account
	// (POST /api/orgs/{orgId}/users/{userId}/accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID)
	// Delete an account
	// (DELETE /api/orgs/{orgId}/users/{userId}/accounts/{accountId})
	DeleteAccount(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, accountID AccountID)
	// Get consents of a user
	// (GET /api/orgs/{orgId}/users/{userId}/consents)
	GetConsents(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, params GetConsentsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDirectoryAuthURL operation middleware
func (siw *ServerInterfaceWrapper) GetDirectoryAuthURL(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDirectoryAuthURL(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleDirectoryCallback operation middleware
func (siw *ServerInterfaceWrapper) HandleDirectoryCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleDirectoryCallbackParams

	// ------------- Required query parameter "id_token" -------------

	if paramValue := r.URL.Query().Get("id_token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id_token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id_token", r.URL.Query(), &params.IDToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleDirectoryCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMockUsers operation middleware
func (siw *ServerInterfaceWrapper) GetMockUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMockUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMockUsers(w, r, orgID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMockUser operation middleware
func (siw *ServerInterfaceWrapper) CreateMockUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMockUser(w, r, orgID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMockUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteMockUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMockUser(w, r, orgID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMockUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateMockUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMockUser(w, r, orgID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccounts(w, r, orgID, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r, orgID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// ------------- Path parameter "accountId" -------------
	var accountID AccountID

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r, orgID, userID, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsents operation middleware
func (siw *ServerInterfaceWrapper) GetConsents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orgId" -------------
	var orgID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "orgId", r.PathValue("orgId"), &orgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orgId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userID MockUserID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConsentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsents(w, r, orgID, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/directory/auth-url", wrapper.GetDirectoryAuthURL)
	m.HandleFunc("GET "+options.BaseURL+"/api/directory/callback", wrapper.HandleDirectoryCallback)
	m.HandleFunc("POST "+options.BaseURL+"/api/logout", wrapper.LogoutUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/me", wrapper.GetCurrentUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{orgId}/users", wrapper.GetMockUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{orgId}/users", wrapper.CreateMockUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}", wrapper.DeleteMockUser)
	m.HandleFunc("PUT "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}", wrapper.UpdateMockUser)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}/accounts", wrapper.GetAccounts)
	m.HandleFunc("POST "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}/accounts", wrapper.CreateAccount)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}/accounts/{accountId}", wrapper.DeleteAccount)
	m.HandleFunc("GET "+options.BaseURL+"/api/orgs/{orgId}/users/{userId}/consents", wrapper.GetConsents)

	return m
}

type GetDirectoryAuthURLRequestObject struct {
}

type GetDirectoryAuthURLResponseObject interface {
	VisitGetDirectoryAuthURLResponse(w http.ResponseWriter) error
}

type GetDirectoryAuthURL200JSONResponse AuthURLResponse

func (response GetDirectoryAuthURL200JSONResponse) VisitGetDirectoryAuthURLResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleDirectoryCallbackRequestObject struct {
	Params HandleDirectoryCallbackParams
}

type HandleDirectoryCallbackResponseObject interface {
	VisitHandleDirectoryCallbackResponse(w http.ResponseWriter) error
}

type HandleDirectoryCallback303ResponseHeaders struct {
	Location  string
	SetCookie string
}

type HandleDirectoryCallback303Response struct {
	Headers HandleDirectoryCallback303ResponseHeaders
}

func (response HandleDirectoryCallback303Response) VisitHandleDirectoryCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(303)
	return nil
}

type LogoutUserRequestObject struct {
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser303ResponseHeaders struct {
	Location  string
	SetCookie string
}

type LogoutUser303Response struct {
	Headers LogoutUser303ResponseHeaders
}

func (response LogoutUser303Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(303)
	return nil
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse UserResponse

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMockUsersRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	Params GetMockUsersParams
}

type GetMockUsersResponseObject interface {
	VisitGetMockUsersResponse(w http.ResponseWriter) error
}

type GetMockUsers200JSONResponse MockUsersResponse

func (response GetMockUsers200JSONResponse) VisitGetMockUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateMockUserRequestObject struct {
	OrgID OrganizationID `json:"orgId"`
	Body  *CreateMockUserJSONRequestBody
}

type CreateMockUserResponseObject interface {
	VisitCreateMockUserResponse(w http.ResponseWriter) error
}

type CreateMockUser201JSONResponse MockUserResponse

func (response CreateMockUser201JSONResponse) VisitCreateMockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteMockUserRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	UserID MockUserID     `json:"userId"`
}

type DeleteMockUserResponseObject interface {
	VisitDeleteMockUserResponse(w http.ResponseWriter) error
}

type DeleteMockUser204Response struct {
}

func (response DeleteMockUser204Response) VisitDeleteMockUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateMockUserRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	UserID MockUserID     `json:"userId"`
	Body   *UpdateMockUserJSONRequestBody
}

type UpdateMockUserResponseObject interface {
	VisitUpdateMockUserResponse(w http.ResponseWriter) error
}

type UpdateMockUser200JSONResponse MockUserResponse

func (response UpdateMockUser200JSONResponse) VisitUpdateMockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountsRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	UserID MockUserID     `json:"userId"`
	Params GetAccountsParams
}

type GetAccountsResponseObject interface {
	VisitGetAccountsResponse(w http.ResponseWriter) error
}

type GetAccounts200JSONResponse AccountsResponse

func (response GetAccounts200JSONResponse) VisitGetAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAccountRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	UserID MockUserID     `json:"userId"`
	Body   *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse AccountResponse

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAccountRequestObject struct {
	OrgID     OrganizationID `json:"orgId"`
	UserID    MockUserID     `json:"userId"`
	AccountID AccountID      `json:"accountId"`
}

type DeleteAccountResponseObject interface {
	VisitDeleteAccountResponse(w http.ResponseWriter) error
}

type DeleteAccount204Response struct {
}

func (response DeleteAccount204Response) VisitDeleteAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetConsentsRequestObject struct {
	OrgID  OrganizationID `json:"orgId"`
	UserID MockUserID     `json:"userId"`
	Params GetConsentsParams
}

type GetConsentsResponseObject interface {
	VisitGetConsentsResponse(w http.ResponseWriter) error
}

type GetConsents200JSONResponse ConsentsResponse

func (response GetConsents200JSONResponse) VisitGetConsentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get the authentication URL for the directory service
	// (GET /api/directory/auth-url)
	GetDirectoryAuthURL(ctx context.Context, request GetDirectoryAuthURLRequestObject) (GetDirectoryAuthURLResponseObject, error)

	// (GET /api/directory/callback)
	HandleDirectoryCallback(ctx context.Context, request HandleDirectoryCallbackRequestObject) (HandleDirectoryCallbackResponseObject, error)
	// Logout the current user
	// (POST /api/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// Get current user information
	// (GET /api/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// List mock users in an organization
	// (GET /api/orgs/{orgId}/users)
	GetMockUsers(ctx context.Context, request GetMockUsersRequestObject) (GetMockUsersResponseObject, error)
	// Create a new user in an organization
	// (POST /api/orgs/{orgId}/users)
	CreateMockUser(ctx context.Context, request CreateMockUserRequestObject) (CreateMockUserResponseObject, error)
	// Delete a mock user in an organization
	// (DELETE /api/orgs/{orgId}/users/{userId})
	DeleteMockUser(ctx context.Context, request DeleteMockUserRequestObject) (DeleteMockUserResponseObject, error)
	// Update a user in an organization
	// (PUT /api/orgs/{orgId}/users/{userId})
	UpdateMockUser(ctx context.Context, request UpdateMockUserRequestObject) (UpdateMockUserResponseObject, error)
	// Get accounts of a user
	// (GET /api/orgs/{orgId}/users/{userId}/accounts)
	GetAccounts(ctx context.Context, request GetAccountsRequestObject) (GetAccountsResponseObject, error)
	// Create a new account
	// (POST /api/orgs/{orgId}/users/{userId}/accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Delete an account
	// (DELETE /api/orgs/{orgId}/users/{userId}/accounts/{accountId})
	DeleteAccount(ctx context.Context, request DeleteAccountRequestObject) (DeleteAccountResponseObject, error)
	// Get consents of a user
	// (GET /api/orgs/{orgId}/users/{userId}/consents)
	GetConsents(ctx context.Context, request GetConsentsRequestObject) (GetConsentsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDirectoryAuthURL operation middleware
func (sh *strictHandler) GetDirectoryAuthURL(w http.ResponseWriter, r *http.Request) {
	var request GetDirectoryAuthURLRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDirectoryAuthURL(ctx, request.(GetDirectoryAuthURLRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDirectoryAuthURL")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDirectoryAuthURLResponseObject); ok {
		if err := validResponse.VisitGetDirectoryAuthURLResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleDirectoryCallback operation middleware
func (sh *strictHandler) HandleDirectoryCallback(w http.ResponseWriter, r *http.Request, params HandleDirectoryCallbackParams) {
	var request HandleDirectoryCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleDirectoryCallback(ctx, request.(HandleDirectoryCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleDirectoryCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleDirectoryCallbackResponseObject); ok {
		if err := validResponse.VisitHandleDirectoryCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request) {
	var request LogoutUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMockUsers operation middleware
func (sh *strictHandler) GetMockUsers(w http.ResponseWriter, r *http.Request, orgID OrganizationID, params GetMockUsersParams) {
	var request GetMockUsersRequestObject

	request.OrgID = orgID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMockUsers(ctx, request.(GetMockUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMockUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMockUsersResponseObject); ok {
		if err := validResponse.VisitGetMockUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMockUser operation middleware
func (sh *strictHandler) CreateMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID) {
	var request CreateMockUserRequestObject

	request.OrgID = orgID

	var body CreateMockUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMockUser(ctx, request.(CreateMockUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMockUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMockUserResponseObject); ok {
		if err := validResponse.VisitCreateMockUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMockUser operation middleware
func (sh *strictHandler) DeleteMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID) {
	var request DeleteMockUserRequestObject

	request.OrgID = orgID
	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMockUser(ctx, request.(DeleteMockUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMockUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMockUserResponseObject); ok {
		if err := validResponse.VisitDeleteMockUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMockUser operation middleware
func (sh *strictHandler) UpdateMockUser(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID) {
	var request UpdateMockUserRequestObject

	request.OrgID = orgID
	request.UserID = userID

	var body UpdateMockUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMockUser(ctx, request.(UpdateMockUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMockUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMockUserResponseObject); ok {
		if err := validResponse.VisitUpdateMockUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccounts operation middleware
func (sh *strictHandler) GetAccounts(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, params GetAccountsParams) {
	var request GetAccountsRequestObject

	request.OrgID = orgID
	request.UserID = userID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccounts(ctx, request.(GetAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountsResponseObject); ok {
		if err := validResponse.VisitGetAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID) {
	var request CreateAccountRequestObject

	request.OrgID = orgID
	request.UserID = userID

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAccount operation middleware
func (sh *strictHandler) DeleteAccount(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, accountID AccountID) {
	var request DeleteAccountRequestObject

	request.OrgID = orgID
	request.UserID = userID
	request.AccountID = accountID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAccount(ctx, request.(DeleteAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAccountResponseObject); ok {
		if err := validResponse.VisitDeleteAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConsents operation middleware
func (sh *strictHandler) GetConsents(w http.ResponseWriter, r *http.Request, orgID OrganizationID, userID MockUserID, params GetConsentsParams) {
	var request GetConsentsRequestObject

	request.OrgID = orgID
	request.UserID = userID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConsents(ctx, request.(GetConsentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConsents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConsentsResponseObject); ok {
		if err := validResponse.VisitGetConsentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3W7bNhR+FYLbxQbIlvOzdfBd4qBbMXfD0uWqCAZaOpZYS6RCUmncwA/Ty73CbvNi",
	"A0n92BalRLbbdENzFYuHh+d855eH9zjgacYZMCXx+B7HQEIQ5t8pD4iinOn/Q5CBoJn9ia8up0hx9D6m",
	"QYxUDChIKDCFqEQCQiogUBBiD8sghpTo/WqZAR5jqQRlEV6tPPwGpKScTThfUGgeUSyjVxdozgUiuYqB",
	"KVpI1MV65eGMCJKCKvQgQcBzpl6F+gfVzDOiYuxhRlK9s173sICbnAoI8ViJHLo1SHmwuJIgWhnndrEf",
	"Vy4iwugHo2crZy6i3owzEjlw/u3hnxQERyFB2cPHiDKCbnJAINXDRySBhRyZQyRVJCToO45uScKFoRc0",
	"BSrqjQ9/o6Pvh9izEt/kIJa1yOb4dQlDmJM8UXh85OE5FylReIwpUyfH2MMpuaNpnuLx8dHpi9OfTn48",
	"feHhlDL78cgr9aNMQQSiUvAN/eBQ8o+cMEVDEgJSXJEEhYAERFQqwSXKuChVkF3SD6Rm7lTh+IcuHY5G",
	"o9Ej0q9KtsZjz6xHXsJNDlLpL5ngGQhFwayHRJHmV5IrnhIdI0myfMVuQSoIz1LNyeERHia3hCZklkAH",
	"zSzhwaKTC8vTGQi9lJK7KbBIxXh8PPKalPwWRCjIXE1pStWEMyWISRQutpvEV4wIQaKn0coWMpnP7DfH",
	"WsvCaj3E3pa6FuQ1xyaW28h5nda5rtDis3cQqMbBxuBNKq/2FJlxJuHJrrKeEptGF4QF8YSHbqyCGILF",
	"BY2o2yF0PYHWzbW77GiD9WxdH7UhlbdlqL3hlY/jSxWk8vMCfVgo+8BXfdBRudS/E8oWRuG7QcQH5WpG",
	"h1Oz4NXfBzTNuLBJTde0MY6oivPZMOCpn+R0sfR1YR3MCFv4OkEKRhKfZNTWXLBwbx/zWn8/0ClPdo5c",
	"xVci6Rt7uUgeN40m2t1tJ1qefdzW9nMtXhtY7m2rAkzvckEU/ElTc3ZVGkOiYKD01+364G2YVJPcDSsW",
	"exvW8DP4wV1GxZcsYAYipab3lRsGaonxOgQFvDN99/nSSW6XKWeXQKRt6psVUhGVy46lq0wD9IUil1e9",
	"eHds1f5babwJu8OJWwDw6h6/Cpmv6dKdlF4X16WeXW2Qzd3Vj6TuqpkRKd9z4c5O2lwtO7czcElZHOUZ",
	"SXbPybX6/cpFm/40fBZYaIi9T4bNHgXrQCj1BKLQfg0PNxBfM4DWeRf3Xx+HyA4H6GfoVls+xXQ75ZBN",
	"PXYNFV2IIcgFVcs3QQyp1X3PUZqZdwR2czXwkHaTKW212/wKS2tvyua8edL5y5fmCBUD0jF9TtgCkSxL",
	"isOGmhlVieZWrZ9lGfbwLQhpmRwNR8ORudZnwLSDjfHJcDQ80UWaqNhorB3Pt4NGLpa+VmlQ9NURGCfW",
	"vlHN0PDPoC5KatO2X07N9Mz6omF5PBqZRMKZAjvqWBPcf1e0TPXs51sBczzG3/j1/NQvRjj+9s3AQLYJ",
	"1dmGFZAWyFg3T1MillZkgyNpEFYQVwAgCeKWBmBYbGETkCSZkWDRis0vhIUJVPBMSvrNMerbe+dcjIZ/",
	"Kb4A1msWeb0F/cnoxOW1gH5XMQg0QJfFUBkpbjExLtMyqnYZpiD1KzozgFaDOmS6dm3G18r8FTgnPOK5",
	"zZpcOsCdmnWd+PC+Sic8ogwVY9Rn1L1OQcYrtpLP22tt3tqNLQD2kSAXAphCOivWnmrzaFvUTuweF4CH",
	"DNiNyuSI1sma6EjnPn3pMVj2hENHddDFzGDCRST9ezPkX/maTHZhVHVPzZB16VyT+FtvDSvv0R3G/Z5I",
	"Z2bxjWA/pNmafaPDdlMqFeJzZHHs7b96t+587H5EGSIMrQNnmmtn8E/0LRJKIfe2zrXNsSDVOQ+XBwex",
	"vJetioZuw2ZHn+C4dpPpdWTu4BD2tphFHRHE4H0ZY02btYeaf2/v9CubnhNQ0DTthfl+MNM+HlBrj42O",
	"kDptlpLXpc8iq0N/IK2OiNTu3+b9ucP57aTkORF6plAZff5QyQ3W/S1sbYTIXmHiF88InTWqfEj5zH7w",
	"XytojfemNotXmO/SgJSbdVUkRTvWXcMKuf4fUbz1uv6J6932C63rLmhJDlPxCuP2C13/vnoLfELZex5v",
	"eJy6fs98Wokscd+3QLJ+oBfvD535snzB+5ovO4Or8dDZ2kyWeO50YSs2r+fL1Wr1bwAAAP//fM860zsn",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
