name: Conformance Suite Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      CS_VERSION: "6111a8e835350b9270a7443a42329628e62f368f"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache Conformance Suite Repository
        uses: actions/cache@v3
        id: cache-cs
        with:
          path: ./conformance-suite
          key: cs-${{ env.CS_VERSION }}

      - name: Set Up Conformance Suite
        if: steps.cache-cs.outputs.cache-hit != 'true'
        run: |
          make setup-cs

      # Only needed if you also want to curl from the host by name.
      - name: Add Host Entries
        run: |
          echo "127.0.0.1 auth.mockbank.local" | sudo tee -a /etc/hosts

      - name: Start containers and wait
        run: |
          set -euxo pipefail

          dump_logs() {
            echo "===== SERVICES ====="
            docker compose --profile conformance config --services || true
            echo "===== PS ====="
            docker compose --profile conformance ps || true
            echo "===== RECENT LOGS (gateway, mockbank, cs-*) ====="
            docker compose logs --no-color --tail=200 gateway mockbank cs-httpd cs-server cs-mongodb || true
          }
          trap 'echo "[TRAP] Failure detected. Collecting diagnostics..."; dump_logs' ERR

          echo "== Versions =="
          docker version
          docker compose version

          echo "== Up stack =="
          docker compose --profile conformance up -d

          echo "== Services =="
          docker compose --profile conformance config --services

          echo "== Containers =="
          docker compose --profile conformance ps

          # ---- helper: wait HTTP from host ----
          wait_http() {
            url="$1"; timeout_s="${2:-120}"
            start=$(date +%s)
            while :; do
              code="$(curl -sk -o /dev/null -w '%{http_code}' "$url" || true)"
              [ "$code" = "200" ] && echo "OK: $url" && return 0
              [ $(( $(date +%s) - start )) -ge "$timeout_s" ] && echo "TIMEOUT ($timeout_s s) for $url (last code: ${code:-000})" && return 1
              echo "Waiting for $url (last code: ${code:-000}); sleep 2s"
              sleep 2
            done
          }

          echo "== Wait CS (host, 8443) =="
          wait_http "https://localhost:8443/api/runner/available" 120

          echo "== (Optional) host OIDC check (expect 502 until backend is ready) =="
          curl -sk -i https://auth.mockbank.local/.well-known/openid-configuration -w "\nHTTP %{http_code}\n" || true

          # ---- compose network name ----
          compose_net="$(docker compose ps -q | head -n1 | xargs -r docker inspect -f '{{range .NetworkSettings.Networks}}{{.NetworkID}}{{end}}' | xargs -r docker network inspect -f '{{.Name}}' || true)"
          echo "== Compose network: ${compose_net:-<unknown>} =="

          # ---- 1) Wait for BACKEND directly (bypass gateway) ----
          # mockbank exposes port 80 internally (see `docker compose ps`)
          echo "== Wait backend (mockbank:80) inside network =="
          start=$(date +%s)
          while :; do
            code="$(docker run --rm --network "$compose_net" curlimages/curl:8.10.1 \
              -s -o /dev/null -w '%{http_code}' \
              http://mockbank/.well-known/openid-configuration || true)"
            if [ "$code" = "200" ]; then
              echo "Backend mockbank is ready (HTTP 200)"
              break
            fi
            if [ $(( $(date +%s) - start )) -ge 300 ]; then
              echo "TIMEOUT (300s) waiting for backend mockbank (last code: ${code:-000})"
              docker compose --profile conformance logs --no-color --tail=200 mockbank || true
              exit 1
            fi
            echo "Backend not ready yet (last code: ${code:-000}); sleep 2s"
            sleep 2
          done

          # ---- 2) Wait for GATEWAY to proxy it successfully ----
          # Keep Host/SNI = auth.mockbank.local, but connect to gateway:443
          echo "== Wait gateway → backend (auth.mockbank.local via gateway) =="
          start=$(date +%s)
          while :; do
            code="$(docker run --rm --network "$compose_net" curlimages/curl:8.10.1 \
              -sk --connect-to auth.mockbank.local:443:gateway:443 \
              -o /dev/null -w '%{http_code}' \
              https://auth.mockbank.local/.well-known/openid-configuration || true)"
            if [ "$code" = "200" ]; then
              echo "Gateway is proxying OK (HTTP 200)"
              break
            fi
            if [ $(( $(date +%s) - start )) -ge 180 ]; then
              echo "TIMEOUT (180s) waiting for gateway to proxy (last code: ${code:-000})"
              echo "---- gateway logs ----"
              docker compose --profile conformance logs --no-color --tail=200 gateway || true
              echo "---- mockbank logs ----"
              docker compose --profile conformance logs --no-color --tail=200 mockbank || true
              exit 1
            fi
            echo "Gateway not ready yet (last code: ${code:-000}); sleep 2s"
            sleep 2
          done

      - name: Run Tests
        run: |
          set -euxo pipefail
          make cs-tests

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mockbank
          path: conformance-suite/results/*.zip

  all-tests-succeeded:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
    steps:
      - name: Test plans passed
        run: echo "All test plans passed successfully!"
