name: Build and Publish Lambda to AWS

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build Lambda binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/main ./cmd/lambda

      - name: Zip Lambda
        run: |
          cd build
          zip main.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::208072937240:role/mockbank-github-oidc
          role-session-name: mockbank-github-ci
          aws-region: us-east-1

      - name: Upload Lambda to S3
        run: |
          aws s3 cp build/main.zip s3://mockbank-lambda-artifacts/mockbank/main.zip
